### ISSUE TITLE
Bot prefix?

### ISSUE THREAD

**Issue by Crossinq** [eric-yeung/Discord-Bot#4]
Hi
i'm new to coding and im looking to make a discord music bot.
i typed in your code and found the prefix
`load_dotenv() 
client = commands.Bot(command_prefix='.')`
but i dont know the play command and i would like to change the prefix.
can i just do "= "v!" and then use the command v!play in the discord? because i tried to do this but i dosent seem to be working,
is that not an option or is the code not right?
-Crossinq

**Comment by eric-yeung** [comment]
If you use .play, thats the function in the actual code. It’s defined as play which leads to the command to be .play but you can change the prefix to whatever you want.

**Comment by Crossinq** [comment]
> If you use .play, thats the function in the actual code. It’s defined as play which leads to the command to be .play but you can change the prefix to whatever you want.

the way to change it is to change the '.' to the prefix i want right? and then the play command is my prefix then v!play song url

**Comment by eric-yeung** [comment]
Yes exactly   
  
  
  
    
  

  
  
>

**Comment by Crossinq** [comment]
i didnt change the prefix bc i wanted to test the original prefix. i typed .play song url and this error came
![image](https://user-images.githubusercontent.com/89217366/130122413-6d90a92d-69c2-4269-936f-47924b76de24.png)

**Comment by eric-yeung** [comment]
Have you installed all the dependencies?
  
  
  
    
  

  
  
>

**Comment by Crossinq** [comment]
i use repl, is that a problem?

**Comment by eric-yeung** [comment]
No but make sure to install the dependencies on the readme.md   
  
  
  
    
  

  
  
>

**Comment by Crossinq** [comment]
when you say install do you mean import? if not then how do i install it... sorry if im a bother but im new to this coding thing :/

**Comment by eric-yeung** [comment]
https://youtu.be/MbhXIddT2YY   Use this tutorial as your base to build it
  
  
  
    
  

  
  
>

**Comment by Crossinq** [comment]
this dosent really help since useing a browser is from my understanding so that you dont have to download anything and i wanna use repl because then i can get 24/7 uptime so imma just find a diffrent code since this clearly isnt working

**Comment by eric-yeung** [comment]
Python naturally doesnt have any APIs to do things like this which is why you need to install the dependencies for the bot to use.
  
  
  
    
  

  
  
>
